<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="em_AU">

<head>

    <base href="<?=$this->application->url();?>" target="_top" />

    <meta http-equiv="content-type" content="text/html; charset=utf-8" />

    <?php

    /**
     * This uses the HTML view helper to include a <title> tag use the app.name directive in your application.ini file.
     */
    echo $this->html->title($this->application->config->app['name']);

    /**
     * This import() method is very important.  It is used to generate any <link> tags that are required by
     * any views and view helpers that you are using.  Without this, you may find some feature of HazaarMVC view helper
     * ecosystem will not work correctly.  The equivalent of this for <script> tags is post().
     */
    echo $this->import();

    /**
     * You can also import a stylesheet directly using the style() method of the HTML view helper:
     *
     * echo $this->html->link('main.css');
     *
     * However it is recommended that stylesheets now be imported using the application.json config.
     */
    ?>

</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="<?=$this->application->url();?>">
                <?=$this->application->config->app['name']; ?>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <?=$this->html->a($this->application->url(), 'Home')->class('nav-link'); ?>
                    </li>
                    <li class="nav-item">
                        <?=$this->html->a($this->url('test'), 'Test')->class('nav-link'); ?>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Help</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown01">
                            <h6 class="dropdown-header">Documentation</h6><?=$this->html->a('http://www.hazaarmvc.com', 'Hazaar MVC Website')->class('dropdown-item'); ?><?=$this->html->a('http://www.hazaarmvc.com/docs', 'Online Documentation')->class('dropdown-item'); ?><?=$this->html->a('http://www.hazaarmvc.com/apidoc', 'API Reference')->class('dropdown-item'); ?>
                            <div class="dropdown-divider"></div>
                            <h6 class="dropdown-header">Support</h6><?=$this->html->a('http://git.hazaarlabs.com/hazaar/hazaar-mvc/issues', 'Support Issues')->class('dropdown-item'); ?><?=$this->html->a('http://git.hazaarlabs.com/hazaar/hazaar-mvc/issues/new', 'Create Issue')->class('dropdown-item'); ?>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <main role="main">

        <?php

        /**
         * The layout() method includes the view that we are currently trying to display.
         */
        echo $this->layout();

        ?>

    </main>

    <footer class="bd-footer text-muted">
        <p class="float-right py-4 px-5">
            <?=$this->html->poweredby(); ?>
        </p>
        <div class="container-fluid p-3 p-md-5">
            <ul class="bd-footer-links">
                <li>
                    <a href="https://git.hazaarlabs.com/hazaar/hazaar-mvc">GitLab</a>
                </li>
                <li>
                    <a href="https://facebook.com/hazaarmvc">Facebook</a>
                </li>
                <li>
                    <a href="https://twitter.com/hazaarmvc">Twitter</a>
                </li>
                <li>
                    <a href="http://hazaarmvc.com/docs/examples">Examples</a>
                </li>
                <li>
                    <a href="http://hazaarmvc.com/about">About</a>
                </li>

            </ul>
            <p>Copyright &copy; Hazaar Labs - 2017</p>

        </div>
    </footer>

    <?php

    /**
     * This post() method is very important.  It is used to generate any <script> tags that are
     * required by your applications and any views and view helpers that you are using.  Without
     * this, you may find some feature of HazaarMVC view helper ecosystem will not work correctly.
     * It's here at the bottom so that pages load faster.
     */

    echo $this->post();

    ?>

</body>
</html>

